# stacks/filebrowser/docker-compose.yml
version: "3.8"

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.31.1
    hostname: filebrowser
    ports:
      - 8082:80
    user: ${PUID}:${PGID}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - "${FILEBROWSER_VOLUME_PATH}/database/filebrowser.db:/database.db:rw"
      - "${MOUNT_PATH:-/}:/srv/:rw"
    network_mode: bridge
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: '1024M'
        reservations:
          cpus: '0.1'
          memory: '64M'
