version: "3.8"

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.29.0
    hostname: filebrowser
    ports:
      - ${FILEBROWSER_HTTP_WEBPORT:-80}:80/tcp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/srv
      - ${DOCKER_VOLUMES_DIR}/filebrowser:/etc/filebrowser:rw
    restart: unless-stopped
    network_mode: bridge
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
