# stacks/filebrowser/docker-compose.yml
version: "3.8"

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.30.0
    hostname: filebrowser
    ports:
      - ${FILEBROWSER_HTTP_WEBPORT:-80}:80/tcp
    user: ${PUID}:${PGID}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - "${FILEBROWSER_VOLUME_PATH}/database/filebrowser.db:/database.db:rw"
      - "${MOUNT_PATH:-/}:/srv/:rw"
    restart: unless-stopped
    network_mode: bridge
    deploy:
      resources:
        limits:
          cpus: "${FILEBROWSER_RESOURCES_CPUS}"
          memory: "${FILEBROWSER_RESOURCES_MEMORY}"
