# stacks/pihole-unbound/docker-compose.yml
version: '3.9'

services:
  pihole:
    image: pihole/pihole:2024.07.0
    container_name: pihole
    hostname: pihole
    depends_on:
      - unbound
    ports:
      - 53:53/udp
      - 1010:80/tcp
    environment:
      - PIHOLE_UID=${PUID}
      - PIHOLE_GID=${PGID}
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - DNSMASQ_LISTENING=${PIHOLE_DNSMASQ_LISTENING}
      - TZ=${PIHOLE_TZ:-IST}
      - CUSTOM_CACHE_SIZE=${PIHOLE_CACHE_SIZE}
      - IPv6=false
      - PIHOLE_DNS_=unbound
      - DNS_BOGUS_PRIV=true
      - DNS_FQDN_REQUIRED=true
      - WEBTHEME=high-contrast-dark
    volumes:
      - "${PIHOLE_VOLUME_PATH}:/etc/pihole/:rw"
      - "${PIHOLE_VOLUME_PATH}/dnsmasq.d:/etc/dnsmasq.d/:rw"
    networks:
      - domain-name-server
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.25'
          memory: '512M'
        reservations:
          cpus: '0.05'
          memory: '256M'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1010/admin/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  unbound:
    container_name: unbound
    image: mvance/unbound:1.20.0
    hostname: unbound
    volumes:
      - "${UNBOUND_VOLUME_PATH}/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf:ro"
      - "${UNBOUND_VOLUME_PATH}/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro"
      - "${UNBOUND_VOLUME_PATH}/srv-records.conf:/opt/unbound/etc/unbound/srv-records.conf:ro"
    networks:
      - domain-name-server
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
        reservations:
          cpus: '0.05'
          memory: '32M'
    healthcheck:
      test: [ "CMD", "dig", "@localhost", "-p", "5335", "example.com" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  domain-name-server:
    name: "dns"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.53.0/24
    external: false
