# stacks/pihole-unbound/docker-compose.yml
version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    hostname: pihole
    ports:
      - ${PIHOLE_DNS_PORT:-53}:53/tcp
      - ${PIHOLE_DNS_PORT:-53}:53/udp
      - ${PIHOLE_HTTP_WEBPORT:-80}:80/tcp
      - ${PIHOLE_HTTPS_WEBPORT:-443}:443/tcp
    environment:
      - PIHOLE_UID=${PUID}
      - PIHOLE_GID=${PGID}
      - PIHOLE_DNS_=unbound
      - IPv6=false
      - DNSMASQ_LISTENING=${PIHOLE_DNSMASQ_LISTENING}
      - DNS_BOGUS_PRIV=true
      - DNS_FQDN_REQUIRED=true
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - WEBTHEME=high-contrast-dark
      - TZ=${PIHOLE_TZ:-IST}
      - CUSTOM_CACHE_SIZE=${PIHOLE_CACHE_SIZE}
    volumes:
      - "${PIHOLE_VOLUME_PATH}:/etc/pihole/:rw"
      - "${PIHOLE_VOLUME_PATH}/dnsmasq.d:/etc/dnsmasq.d/:rw"
    networks:
      - dns
    restart: unless-stopped
    depends_on:
      - unbound
    deploy:
      resources:
        limits:
          cpus: "${PIHOLE_RESOURCES_CPUS}"
          memory: "${PIHOLE_RESOURCES_MEMORY}"
  unbound:
    container_name: unbound
    image: mvance/unbound:1.20.0
    hostname: unbound
    volumes:
      - "${UNBOUND_VOLUME_PATH}/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf:r"
      - "${UNBOUND_VOLUME_PATH}/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:r"
      - "${UNBOUND_VOLUME_PATH}/srv-records.conf:/opt/unbound/etc/unbound/srv-records.conf:r"
    networks:
      - dns
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "${UNBOUND_RESOURCES_CPUS}"
          memory: "${UNBOUND_RESOURCES_MEMORY}"

networks:
  dns:
    driver: bridge
