# stacks/pihole-unbound/docker-compose.yml
version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.05.0
    hostname: pihole
    user: ${PUID}:${PGID}
    ports:
      - ${PIHOLE_DNS_PORT:-53}:53/tcp
      - ${PIHOLE_DNS_PORT:-53}:53/udp
      - ${PIHOLE_HTTP_WEBPORT:-80}:80/tcp
      - ${PIHOLE_HTTPS_WEBPORT:-443}:443/tcp
    environment:
      - TZ=${PIHOLE_TZ:-IST}
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - PIHOLE_DNS_=unbound
      - DNS_BOGUS_PRIV=true
      - DNS_FQDN_REQUIRED=true
      - IPv6=false
      - WEBTHEME=high-contrast-dark
      - DNSMASQ_LISTENING=all
    volumes:
      - "${PIHOLE_VOLUME_PATH}:/etc/pihole/:rw"
      - "${PIHOLE_VOLUME_PATH}/dnsmasq.d:/etc/dnsmasq.d/:rw"
    networks:
      - dns
    restart: unless-stopped
    depends_on:
      - unbound
    deploy:
      resources:
        limits:
          cpus: "${PIHOLE_RESOURCES_CPUS}"
          memory: "${PIHOLE_RESOURCES_MEMORY}"
  unbound:
    container_name: unbound
    image: mvance/unbound:1.19.3
    hostname: unbound
    user: ${PUID}:${PGID}
    volumes:
      - "${UNBOUND_VOLUME_PATH}:/opt/unbound/etc/unbound/:rw"
    networks:
      - dns
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "${UNBOUND_RESOURCES_CPUS}"
          memory: "${UNBOUND_RESOURCES_MEMORY}"

networks:
  dns:
    driver: bridge
