# stacks/cloudflared/docker-compose.yml
version: '3.9'

services:
  cloudflared:
    image: cloudflare/cloudflared:2024.9.1
    container_name: cloudflared
    hostname: cloudflared
    user: ${PUID}:${PGID}
    environment:
      TUNNEL_TOKEN: "${CLOUDFLARED_TUNNEL_TOKEN}"
    command: tunnel --no-autoupdate run
    volumes:
      - "${CLOUDFLARED_VOLUME_PATH}:/etc/cloudflared/:rw"
    network_mode: bridge
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: '1024M'
        reservations:
          cpus: '0.1'
          memory: '64M'
