# stacks/nginx-proxy-manager/docker-compose.yml
version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:v3
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - ${NPM_HTTP_PORT:-80}:80/tcp
      - ${NPM_HTTPS_PORT:-443}:443/tcp
      - ${NPM_HTTP_WEBPORT:-81}:81/tcp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DISABLE_IPV6=true
      # Comment below line if you are not interested in using the sqlite
      - DB_SQLITE_FILE=/data/database.sqlite
      # Uncomment below lines if you wanted to use external DB
      - DB_MYSQL_HOST=${DB_HOST:-localhost}
      - DB_MYSQL_PORT=${DB_PORT:-3306}
      - DB_MYSQL_USER=${DB_USER}
      - DB_MYSQL_PASSWORD=${DB_PASSWORD}
      - DB_MYSQL_NAME=${DB_NAME}
    volumes:
      - "${NPM_VOLUME_PATH}/data:/data/:rw"
      - "${NPM_VOLUME_PATH}/letsencrypt:/etc/letsencrypt/:rw"
      - "${NPM_VOLUME_PATH}/letsencrypt/log:/tmp/letsencrypt-log/:rw"
    network_mode: bridge
    deploy:
      resources:
        limits:
          cpus: "${NPM_RESOURCES_CPUS}"
          memory: "${NPM_RESOURCES_MEMORY}"
