# .github/workflows/enforcer.yaml
name: 'Pull Request Validation'

on:
  pull_request:
    branches: [main, dev, alpha]

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is to main
        if: github.base_ref == 'main' && github.head_ref != 'alpha'
        run: |
          echo "ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}."
          exit 1

      - name: Check if PR is to alpha
        if: github.base_ref == 'alpha' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}."
          exit 1

      - name: Check if PR is to dev
        if: github.base_ref == 'dev' 
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^feature/.+$ ]]; then 
            echo "ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}."
            exit 1
          fi
